version: '3.8'

services:
  data-assistant:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STREAMLIT_SERVER_PORT=8080
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    volumes:
      - ./new_data_assistant_project/data:/app/new_data_assistant_project/data
      - ./new_data_assistant_project/src/database:/app/new_data_assistant_project/src/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
