services:
  streamlit-app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - ENVIRONMENT=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - streamlit-app
    ports:
      - "80:80"
    volumes:
      - ./nginx/streamlit.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
